"""MT5 constants for trading operations, timeframes, and data retrieval."""

from syntiq_mt5._core.mt5_import import mt5

# Trade Actions
TRADE_ACTION_DEAL = getattr(mt5, "TRADE_ACTION_DEAL", 1)
TRADE_ACTION_PENDING = getattr(mt5, "TRADE_ACTION_PENDING", 5)
TRADE_ACTION_SLTP = getattr(mt5, "TRADE_ACTION_SLTP", 6)
TRADE_ACTION_MODIFY = getattr(mt5, "TRADE_ACTION_MODIFY", 7)
TRADE_ACTION_REMOVE = getattr(mt5, "TRADE_ACTION_REMOVE", 8)
TRADE_ACTION_CLOSE_BY = getattr(mt5, "TRADE_ACTION_CLOSE_BY", 10)

# Order Types
ORDER_TYPE_BUY = getattr(mt5, "ORDER_TYPE_BUY", 0)
ORDER_TYPE_SELL = getattr(mt5, "ORDER_TYPE_SELL", 1)
ORDER_TYPE_BUY_LIMIT = getattr(mt5, "ORDER_TYPE_BUY_LIMIT", 2)
ORDER_TYPE_SELL_LIMIT = getattr(mt5, "ORDER_TYPE_SELL_LIMIT", 3)
ORDER_TYPE_BUY_STOP = getattr(mt5, "ORDER_TYPE_BUY_STOP", 4)
ORDER_TYPE_SELL_STOP = getattr(mt5, "ORDER_TYPE_SELL_STOP", 5)
ORDER_TYPE_BUY_STOP_LIMIT = getattr(mt5, "ORDER_TYPE_BUY_STOP_LIMIT", 6)
ORDER_TYPE_SELL_STOP_LIMIT = getattr(mt5, "ORDER_TYPE_SELL_STOP_LIMIT", 7)
ORDER_TYPE_CLOSE_BY = getattr(mt5, "ORDER_TYPE_CLOSE_BY", 8)

# Order Filling
ORDER_FILLING_FOK = getattr(mt5, "ORDER_FILLING_FOK", 0)
ORDER_FILLING_IOC = getattr(mt5, "ORDER_FILLING_IOC", 1)
ORDER_FILLING_RETURN = getattr(mt5, "ORDER_FILLING_RETURN", 2)
ORDER_FILLING_BOC = getattr(mt5, "ORDER_FILLING_BOC", 3)

# Order Time
ORDER_TIME_GTC = getattr(mt5, "ORDER_TIME_GTC", 0)
ORDER_TIME_DAY = getattr(mt5, "ORDER_TIME_DAY", 1)
ORDER_TIME_SPECIFIED = getattr(mt5, "ORDER_TIME_SPECIFIED", 2)
ORDER_TIME_SPECIFIED_DAY = getattr(mt5, "ORDER_TIME_SPECIFIED_DAY", 3)

# Position Types
POSITION_TYPE_BUY = getattr(mt5, "POSITION_TYPE_BUY", 0)
POSITION_TYPE_SELL = getattr(mt5, "POSITION_TYPE_SELL", 1)

# Timeframes
TIMEFRAME_M1 = getattr(mt5, "TIMEFRAME_M1", 1)
TIMEFRAME_M2 = getattr(mt5, "TIMEFRAME_M2", 2)
TIMEFRAME_M3 = getattr(mt5, "TIMEFRAME_M3", 3)
TIMEFRAME_M4 = getattr(mt5, "TIMEFRAME_M4", 4)
TIMEFRAME_M5 = getattr(mt5, "TIMEFRAME_M5", 5)
TIMEFRAME_M6 = getattr(mt5, "TIMEFRAME_M6", 6)
TIMEFRAME_M10 = getattr(mt5, "TIMEFRAME_M10", 10)
TIMEFRAME_M12 = getattr(mt5, "TIMEFRAME_M12", 12)
TIMEFRAME_M15 = getattr(mt5, "TIMEFRAME_M15", 15)
TIMEFRAME_M20 = getattr(mt5, "TIMEFRAME_M20", 20)
TIMEFRAME_M30 = getattr(mt5, "TIMEFRAME_M30", 30)
TIMEFRAME_H1 = getattr(mt5, "TIMEFRAME_H1", 16385)
TIMEFRAME_H2 = getattr(mt5, "TIMEFRAME_H2", 16386)
TIMEFRAME_H3 = getattr(mt5, "TIMEFRAME_H3", 16387)
TIMEFRAME_H4 = getattr(mt5, "TIMEFRAME_H4", 16388)
TIMEFRAME_H6 = getattr(mt5, "TIMEFRAME_H6", 16390)
TIMEFRAME_H8 = getattr(mt5, "TIMEFRAME_H8", 16392)
TIMEFRAME_H12 = getattr(mt5, "TIMEFRAME_H12", 16396)
TIMEFRAME_D1 = getattr(mt5, "TIMEFRAME_D1", 16408)
TIMEFRAME_W1 = getattr(mt5, "TIMEFRAME_W1", 32769)
TIMEFRAME_MN1 = getattr(mt5, "TIMEFRAME_MN1", 49153)

# Copy Ticks Flags
COPY_TICKS_ALL = getattr(mt5, "COPY_TICKS_ALL", 6)
COPY_TICKS_INFO = getattr(mt5, "COPY_TICKS_INFO", 2)
COPY_TICKS_TRADE = getattr(mt5, "COPY_TICKS_TRADE", 4)

# Tick Flags
TICK_FLAG_BID = getattr(mt5, "TICK_FLAG_BID", 2)
TICK_FLAG_ASK = getattr(mt5, "TICK_FLAG_ASK", 4)
TICK_FLAG_LAST = getattr(mt5, "TICK_FLAG_LAST", 8)
TICK_FLAG_VOLUME = getattr(mt5, "TICK_FLAG_VOLUME", 16)
TICK_FLAG_BUY = getattr(mt5, "TICK_FLAG_BUY", 32)
TICK_FLAG_SELL = getattr(mt5, "TICK_FLAG_SELL", 64)

# Trade Return Codes
TRADE_RETCODE_REQUOTE = getattr(mt5, "TRADE_RETCODE_REQUOTE", 10004)
TRADE_RETCODE_REJECT = getattr(mt5, "TRADE_RETCODE_REJECT", 10006)
TRADE_RETCODE_CANCEL = getattr(mt5, "TRADE_RETCODE_CANCEL", 10007)
TRADE_RETCODE_PLACED = getattr(mt5, "TRADE_RETCODE_PLACED", 10008)
TRADE_RETCODE_DONE = getattr(mt5, "TRADE_RETCODE_DONE", 10009)
TRADE_RETCODE_DONE_PARTIAL = getattr(mt5, "TRADE_RETCODE_DONE_PARTIAL", 10010)
TRADE_RETCODE_ERROR = getattr(mt5, "TRADE_RETCODE_ERROR", 10011)
TRADE_RETCODE_TIMEOUT = getattr(mt5, "TRADE_RETCODE_TIMEOUT", 10012)
TRADE_RETCODE_INVALID = getattr(mt5, "TRADE_RETCODE_INVALID", 10013)
TRADE_RETCODE_INVALID_VOLUME = getattr(mt5, "TRADE_RETCODE_INVALID_VOLUME", 10014)
TRADE_RETCODE_INVALID_PRICE = getattr(mt5, "TRADE_RETCODE_INVALID_PRICE", 10015)
TRADE_RETCODE_INVALID_STOPS = getattr(mt5, "TRADE_RETCODE_INVALID_STOPS", 10016)
TRADE_RETCODE_TRADE_DISABLED = getattr(mt5, "TRADE_RETCODE_TRADE_DISABLED", 10017)
TRADE_RETCODE_MARKET_CLOSED = getattr(mt5, "TRADE_RETCODE_MARKET_CLOSED", 10018)
TRADE_RETCODE_NO_MONEY = getattr(mt5, "TRADE_RETCODE_NO_MONEY", 10019)
TRADE_RETCODE_PRICE_CHANGED = getattr(mt5, "TRADE_RETCODE_PRICE_CHANGED", 10020)
TRADE_RETCODE_PRICE_OFF = getattr(mt5, "TRADE_RETCODE_PRICE_OFF", 10021)
TRADE_RETCODE_INVALID_EXPIRATION = getattr(mt5, "TRADE_RETCODE_INVALID_EXPIRATION", 10022)
TRADE_RETCODE_ORDER_CHANGED = getattr(mt5, "TRADE_RETCODE_ORDER_CHANGED", 10023)
TRADE_RETCODE_TOO_MANY_REQUESTS = getattr(mt5, "TRADE_RETCODE_TOO_MANY_REQUESTS", 10024)
TRADE_RETCODE_NO_CHANGES = getattr(mt5, "TRADE_RETCODE_NO_CHANGES", 10025)
TRADE_RETCODE_SERVER_DISABLES_AT = getattr(mt5, "TRADE_RETCODE_SERVER_DISABLES_AT", 10026)
TRADE_RETCODE_CLIENT_DISABLES_AT = getattr(mt5, "TRADE_RETCODE_CLIENT_DISABLES_AT", 10027)
TRADE_RETCODE_LOCKED = getattr(mt5, "TRADE_RETCODE_LOCKED", 10028)
TRADE_RETCODE_FROZEN = getattr(mt5, "TRADE_RETCODE_FROZEN", 10029)
TRADE_RETCODE_INVALID_FILL = getattr(mt5, "TRADE_RETCODE_INVALID_FILL", 10030)
TRADE_RETCODE_CONNECTION = getattr(mt5, "TRADE_RETCODE_CONNECTION", 10031)
TRADE_RETCODE_ONLY_REAL = getattr(mt5, "TRADE_RETCODE_ONLY_REAL", 10032)
TRADE_RETCODE_LIMIT_ORDERS = getattr(mt5, "TRADE_RETCODE_LIMIT_ORDERS", 10033)
TRADE_RETCODE_LIMIT_VOLUME = getattr(mt5, "TRADE_RETCODE_LIMIT_VOLUME", 10034)
TRADE_RETCODE_INVALID_ORDER = getattr(mt5, "TRADE_RETCODE_INVALID_ORDER", 10035)
TRADE_RETCODE_POSITION_CLOSED = getattr(mt5, "TRADE_RETCODE_POSITION_CLOSED", 10036)

# ruff: noqa: RUF022
__all__ = [
    # Trade Actions
    "TRADE_ACTION_DEAL",
    "TRADE_ACTION_PENDING",
    "TRADE_ACTION_SLTP",
    "TRADE_ACTION_MODIFY",
    "TRADE_ACTION_REMOVE",
    "TRADE_ACTION_CLOSE_BY",
    # Order Types
    "ORDER_TYPE_BUY",
    "ORDER_TYPE_SELL",
    "ORDER_TYPE_BUY_LIMIT",
    "ORDER_TYPE_SELL_LIMIT",
    "ORDER_TYPE_BUY_STOP",
    "ORDER_TYPE_SELL_STOP",
    "ORDER_TYPE_BUY_STOP_LIMIT",
    "ORDER_TYPE_SELL_STOP_LIMIT",
    "ORDER_TYPE_CLOSE_BY",
    # Order Filling
    "ORDER_FILLING_FOK",
    "ORDER_FILLING_IOC",
    "ORDER_FILLING_RETURN",
    "ORDER_FILLING_BOC",
    # Order Time
    "ORDER_TIME_GTC",
    "ORDER_TIME_DAY",
    "ORDER_TIME_SPECIFIED",
    "ORDER_TIME_SPECIFIED_DAY",
    # Position Types
    "POSITION_TYPE_BUY",
    "POSITION_TYPE_SELL",
    # Timeframes
    "TIMEFRAME_M1",
    "TIMEFRAME_M2",
    "TIMEFRAME_M3",
    "TIMEFRAME_M4",
    "TIMEFRAME_M5",
    "TIMEFRAME_M6",
    "TIMEFRAME_M10",
    "TIMEFRAME_M12",
    "TIMEFRAME_M15",
    "TIMEFRAME_M20",
    "TIMEFRAME_M30",
    "TIMEFRAME_H1",
    "TIMEFRAME_H2",
    "TIMEFRAME_H3",
    "TIMEFRAME_H4",
    "TIMEFRAME_H6",
    "TIMEFRAME_H8",
    "TIMEFRAME_H12",
    "TIMEFRAME_D1",
    "TIMEFRAME_W1",
    "TIMEFRAME_MN1",
    # Copy Ticks Flags
    "COPY_TICKS_ALL",
    "COPY_TICKS_INFO",
    "COPY_TICKS_TRADE",
    # Tick Flags
    "TICK_FLAG_BID",
    "TICK_FLAG_ASK",
    "TICK_FLAG_LAST",
    "TICK_FLAG_VOLUME",
    "TICK_FLAG_BUY",
    "TICK_FLAG_SELL",
    # Trade Return Codes
    "TRADE_RETCODE_REQUOTE",
    "TRADE_RETCODE_REJECT",
    "TRADE_RETCODE_CANCEL",
    "TRADE_RETCODE_PLACED",
    "TRADE_RETCODE_DONE",
    "TRADE_RETCODE_DONE_PARTIAL",
    "TRADE_RETCODE_ERROR",
    "TRADE_RETCODE_TIMEOUT",
    "TRADE_RETCODE_INVALID",
    "TRADE_RETCODE_INVALID_VOLUME",
    "TRADE_RETCODE_INVALID_PRICE",
    "TRADE_RETCODE_INVALID_STOPS",
    "TRADE_RETCODE_TRADE_DISABLED",
    "TRADE_RETCODE_MARKET_CLOSED",
    "TRADE_RETCODE_NO_MONEY",
    "TRADE_RETCODE_PRICE_CHANGED",
    "TRADE_RETCODE_PRICE_OFF",
    "TRADE_RETCODE_INVALID_EXPIRATION",
    "TRADE_RETCODE_ORDER_CHANGED",
    "TRADE_RETCODE_TOO_MANY_REQUESTS",
    "TRADE_RETCODE_NO_CHANGES",
    "TRADE_RETCODE_SERVER_DISABLES_AT",
    "TRADE_RETCODE_CLIENT_DISABLES_AT",
    "TRADE_RETCODE_LOCKED",
    "TRADE_RETCODE_FROZEN",
    "TRADE_RETCODE_INVALID_FILL",
    "TRADE_RETCODE_CONNECTION",
    "TRADE_RETCODE_ONLY_REAL",
    "TRADE_RETCODE_LIMIT_ORDERS",
    "TRADE_RETCODE_LIMIT_VOLUME",
    "TRADE_RETCODE_INVALID_ORDER",
    "TRADE_RETCODE_POSITION_CLOSED",
]
